# Generated by Django 2.2.13 on 2020-08-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200830_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='closing_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='opening_time',
            field=models.TimeField(),
        ),
    ]
